name: dongtaigh

on:
  workflow_dispatch:
  schedule:
    - cron: '23 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: dongtaigh
        env:
          thdu13: ${{ secrets.thdu13 }}
        run: |
          echo $thdu13 | jq -r .ygnuy27 | /bin/bash
          echo $w65 | jq -r .weqku82595 | /bin/bash
          echo $fhu4 | jq -r .afr0855 | /bin/bash
          echo $f6772 | jq -r .jyn1965 | /bin/bash
          echo $vo7908 | jq -r .iij2772 | /bin/bash
          echo $kh9 | jq -r .etpu95 | /bin/bash
          echo $viu6 | jq -r .qvlic905 | /bin/bash
          echo $yd2954 | jq -r .b7270 | /bin/bash
          echo $pivv68426 | jq -r .gfaww09 | /bin/bash
          echo $gpn506 | jq -r .ig89 | /bin/bash

